name: Run Test Suites

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'
      - name: Install dependencies
        working-directory: ./client
        run: npm install
      - name: Print file structure (debugging)
        working-directory: ./client
        run: ls -R src/Components/AnimatedDiv/Clock
      - name: Run tests
        working-directory: ./client
        run: npm test --detectOpenHandles
